### ISSUE TITLE
running the actual build fails with missing gradle wrapper class

### ISSUE THREAD

**Issue by honzik666** [rsksmart/artifacts#1]
The example run of the buildmachine image:

``` 
docker run -v $(pwd):/rskj -w /rskj -ti buildmachine:latest /bin/bash
root@8c9163138a64:/rskj# ./gradlew shadow
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

The gradle seems missing from the top level image or not sure why it cannot be found.

**Comment by bcodesido** [comment]
Thanks for the report. 
We updated our documentation in the [reproducible build](https://github.com/rsksmart/rskj/wiki/Reproducible-Build) article in the [rskj wiki](https://github.com/rsksmart/rskj/wiki).

**Comment by honzik666** [comment]
Not sure, what you mean by the update, the snippet how to run the build is still the same just the security chain verification is now more ellaborate.
Let me know how to clarify this.

Thanks,

Jan

**Comment by bcodesido** [comment]
The script you run to secure the chain downloads and verify the gradle wrapper. 
That should solve the issue. :smile:

**Comment by honzik666** [comment]
I am not sure what you mean by the comment. The script fails with the above error. I have checked out the latest tag GINGER-0.2.1. Looking at the origin, I don't see any recent fixes inside the script. I am assuming that the documentation should somehow reflect what needs to be done to build it inside the docker.

The example I gave was a shell session inside of the container so that I could investigate why it cannot find/download gradle. The container can reach the Internet.

**Comment by bcodesido** [comment]
We have already fixed the [README.md](https://github.com/rsksmart/artifacts/blob/master/Dockerfiles/BUILD/README.md) to reflect what needs to be done.

**Comment by honzik666** [comment]
I hope you won't take this as an offense. I am aware of the reproducible parameter but this is not the problem here. The thing just can't find the gradle class. Nothing is being downloaded, just this plain error. Is the Docker file missing any important part that needs to be part of the image then?

```bash
docker run -v $(pwd):/rskj -w /rskj -ti rsk-buildmachine:latest ./gradlew shadow reproducible
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

I have tested the above on the current master branch of rskj and the result is exactly the same.

**Comment by bcodesido** [comment]
The docker container purpose is to [reproduce the build](https://github.com/rsksmart/rskj/wiki/Reproducible-Build), the [README.md](https://github.com/rsksmart/artifacts/blob/master/Dockerfiles/BUILD/README.md) says that. Following the [reproducible build procedure](https://github.com/rsksmart/rskj/wiki/Reproducible-Build) you will found that is needed to [verify the secure chain](https://github.com/rsksmart/rskj/wiki/Ensure-security-chain-of-RskJ-source-code). The secure chain verification also initialize the repo once is cloned by download your missing gradle wrapper.

**Comment by honzik666** [comment]
Thank you that explains the whole issue. I didn't need the verification for the test build and thus didn't run the configure.sh
